# Generated by Django 5.0.2 on 2024-02-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_crop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='farm_id',
            new_name='farm',
        ),
    ]
