# Generated by Django 5.0.2 on 2024-03-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_expense_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
