# Generated by Django 5.0.2 on 2024-03-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.expense'),
        ),
    ]
