# Generated by Django 5.0.2 on 2024-03-08 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_sale_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_sales', to='app.sale'),
        ),
    ]
