# Generated by Django 5.0.2 on 2024-03-09 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_farmer_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.farm'),
        ),
    ]
