# Generated by Django 5.0.2 on 2024-03-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_expense_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
